// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE2oZFNwOn-dOBAtfR1eUHIGxN0VHJQQA',
    appId: '1:1078722058074:android:5b1bff4a0a134488484563',
    messagingSenderId: '1078722058074',
    projectId: 'chat-app-a78fb',
    storageBucket: 'chat-app-a78fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVL2JrunI055ilDr99tAd9s79jYy-dfVQ',
    appId: '1:1078722058074:ios:8b769486241a5f79484563',
    messagingSenderId: '1078722058074',
    projectId: 'chat-app-a78fb',
    storageBucket: 'chat-app-a78fb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVL2JrunI055ilDr99tAd9s79jYy-dfVQ',
    appId: '1:1078722058074:ios:8b769486241a5f79484563',
    messagingSenderId: '1078722058074',
    projectId: 'chat-app-a78fb',
    storageBucket: 'chat-app-a78fb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}